# Generated by Django 3.0.5 on 2020-05-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Continuous_shooting',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Focus_type',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Link',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Max_resolution',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Optical_zoom',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Screen_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Style',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Video_resolution',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Wireless_communication_technology',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
