# Generated by Django 3.0.5 on 2020-06-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cam', '0002_auto_20200526_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='product-img/'),
        ),
    ]
