# Generated by Django 3.0.5 on 2020-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cam', '0004_auto_20200607_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='Image_Link',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
