# Generated by Django 3.0.5 on 2020-07-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cam', '0005_auto_20200729_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Screen_size',
        ),
    ]
