# Generated by Django 3.0.5 on 2020-07-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cam', '0006_remove_product_screen_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Optical_zoom',
        ),
    ]
